export default function Sticky() {
  return (
    <div className="relative">
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>

      <div className="sticky top-[40px]">Sticky</div>

      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
      <div>Love</div>
    </div>
  );
}
